relativeURLs = true
title = "Benjamin Enke"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Associate Professor, Department of Economics, Harvard University"                
    shortbio2 = "Faculty Research Fellow, NBER"
    logo = "enke.jpg" 
    contact = """
__Email__: [enke@fas.harvard.edu](enke@fas.harvard.edu)  

[[Google Scholar](https://scholar.google.de/citations?user=8-x_XN4AAAAJ&hl=en)]
[[Twitter](https://twitter.com/BenjaminEnke)]"""
    
